#ifndef __PatcherAbout__
#define __PatcherAbout__

/**
@file
Subclass of About, which is generated by wxFormBuilder.
*/

#include "patcher.h"

/** Implementing About */
class PatcherAbout : public About
{
public:
	/** Constructor */
	PatcherAbout( wxWindow* parent );
};

#endif // __PatcherAbout__
